AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/*.yml'
  DisplayStyleGuide: true
  ExtraDetails: true
  SuggestExtensions:
    rubocop-rails: [ rails ]
    rubocop-rspec: [ rspec, rspec-rails ]

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/CaseIndentation:
  IndentOneStep: true
  Enabled: true
  EnforcedStyle: end

Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'config/application.rb'

Metrics/BlockLength:
  Max: 32
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'
    - 'config/routes.rb'
    - 'config/initializers/devise.rb'
    - 'config/environments/*.rb'